name: analysis_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.8,<3.9
  - dataclasses == 0.8
  - matplotlib == 3.4.2
  - notebook == 6.4.3
  - numpy == 1.21.2
  - pandas == 1.3.1
  - pip == 21.2.4
  - scikit-image == 0.18.1
  - scikit-learn == 0.24.2
  - scipy == 1.7.1
  - seaborn == 0.11.2
  - statsmodels == 0.12.2
  - tabulate == 0.8.9
  - git
  - pip:
    - opencv-python == 4.5.4.58
    - black == 19.10b0
    - dataframe-image == 0.1.1
    - git+https://github.com/wjakewright/Activity_Viewer.git
    - -e.

