from dataclasses import dataclass

import numpy as np


@dataclass
class Spine_Coactivity_Data:
    """Dataclass for storing data of a single day following grouped_coactivity_analysis across
        all mice in a given group"""

    day: str
    mouse_id: list
    FOV: list
    parameters: dict
    spine_flags: list
    followup_flags: list
    spine_volumes: np.array
    spine_volumes_um: np.array
    followup_volumes: np.array
    followup_volumes_um: np.array
    movement_spines: np.array
    nonmovement_spines: np.array
    rwd_movement_spines: np.array
    rwd_nonmovement_spines: np.array
    movement_dendrites: np.array
    nonmovement_dendrites: np.array
    rwd_movement_dendrites: np.array
    rwd_nonmovement_dendrites: np.array
    spine_activity_rate: np.array
    dend_activity_rate: np.array
    distance_coactivity_rate: np.array
    distance_coactivity_rate_norm: np.array
    MRS_distance_coactivity_rate: np.array
    MRS_distance_coactivity_rate_norm: np.array
    nMRS_distance_coactivity_rate: np.array
    nMRS_distance_coactivity_rate_norm: np.array
    avg_local_coactivity_rate: np.array
    avg_local_coactivity_rate_norm: np.array
    avg_MRS_local_coactivity_rate: np.array
    avg_MRS_local_coactivity_rate_norm: np.array
    avg_nMRS_local_coactivity_rate: np.array
    avg_nMRS_local_coactivity_rate_norm: np.array
    spine_cluster_score: np.array
    spine_coactive_num: np.array
    MRS_cluster_score: np.array
    MRS_coactive_num: np.array
    nMRS_cluster_score: np.array
    nMRS_coactive_num: np.array
    movement_cluster_score: np.array
    movement_coactive_num: np.array
    nonmovement_cluster_score: np.array
    nonmovement_coactive_num: np.array
    avg_nearby_spine_rate: np.array
    avg_nearby_coactive_spine_rate: np.array
    rel_nearby_spine_rate: np.array
    rel_nearby_coactive_spine_rate: np.array
    frac_nearby_MRSs: np.array
    nearby_coactive_spine_volumes: np.array
    local_coactivity_rate: np.array
    local_coactivity_rate_norm: np.array
    local_spine_fraction_coactive: np.array
    local_spine_coactive_amplitude: np.array
    local_spine_coactive_calcium: np.array
    local_spine_coactive_auc: np.array
    local_spine_coactive_calcium_auc: np.array
    local_spine_coactive_traces: list
    local_spine_coactive_calcium_traces: list
    local_spine_noncoactive_amplitude: np.array
    local_spine_noncoactive_calcium: np.array
    local_spine_noncoactive_auc: np.array
    local_spine_noncoactive_calcium_auc: np.array
    local_spine_noncoactive_traces: list
    local_spine_noncoactive_calcium_traces: list
    local_avg_coactive_spine_num: np.array
    local_sum_nearby_amplitude: np.array
    local_avg_nearby_amplitude: np.array
    local_sum_nearby_calcium: np.array
    local_avg_nearby_calcium: np.array
    local_sum_nearby_calcium_auc: np.array
    local_avg_nearby_calcium_auc: np.array
    local_avg_coactive_num_before: np.array
    local_sum_nearby_amplitude_before: np.array
    local_avg_nearby_amplitude_before: np.array
    local_sum_nearby_calcium_before: np.array
    local_avg_nearby_calcium_before: np.array
    local_avg_relative_nearby_onset: np.array
    local_sum_nearby_binary_traces: list
    local_sum_nearby_spine_traces: list
    local_avg_nearby_spine_traces: list
    local_sum_nearby_calcium_traces: list
    local_avg_nearby_calcium_traces: list
    avg_nearby_movement_correlation: np.array
    avg_nearby_movement_reliability: np.array
    avg_nearby_movement_specificity: np.array
    avg_nearby_coactivity_rate: np.array
    relative_local_coactivity_rate: np.array
    frac_local_coactivity_participation: np.array
    spine_dend_coactivity_rate: np.array
    spine_dend_coactivity_rate_norm: np.array
    spine_dend_spine_fraction_coactive: np.array
    spine_dend_dend_fraction_coactive: np.array
    spine_dend_spine_coactive_amplitude: np.array
    spine_dend_spine_coactive_calcium: np.array
    spine_dend_spine_coactive_auc: np.array
    spine_dend_spine_coactive_calcium_auc: np.array
    spine_dend_dend_coactive_amplitude: np.array
    spine_dend_dend_coactive_auc: np.array
    spine_dend_relative_onset: np.array
    spine_dend_spine_coactive_traces: list
    spine_dend_spine_coactive_calcium_traces: list
    spine_dend_dend_coactive_traces: list
    conj_coactivity_rate: np.array
    conj_coactivity_rate_norm: np.array
    conj_spine_fraction_coactive: np.array
    conj_dend_fraction_coactive: np.array
    conj_spine_coactive_amplitude: np.array
    conj_spine_coactive_calcium: np.array
    conj_spine_coactive_auc: np.array
    conj_spine_coactive_calcium_auc: np.array
    conj_dend_coactive_amplitude: np.array
    conj_denc_coactive_auc: np.array
    conj_relative_onset: np.array
    conj_spine_coactive_traces: list
    conj_spine_coactive_calcium_traces: list
    conj_dend_coactive_traces: list
    nonconj_coactivity_rate: np.array
    nonconj_coactivity_rate_norm: np.array
    nonconj_spine_fraction_coactive: np.array
    nonconj_dend_fraction_coactive: np.array
    nonconj_spine_coactive_amplitude: np.array
    nonconj_spine_coactive_calcium: np.array
    nonconj_spine_coactive_auc: np.array
    nonconj_spine_coactive_calcium_auc: np.array
    nonconj_dend_coactive_amplitude: np.array
    nonconj_dend_coactive_auc: np.array
    nonconj_relative_onset: np.array
    nonconj_spine_coactive_traces: list
    nonconj_spine_coactive_calcium_traces: list
    nonconj_dend_coactive_traces: list
    spine_dend_distance_coactivity_rate: np.array
    spine_dend_distance_coactivity_rate_norm: np.array
    spine_dend_avg_local_coactivity_rate: np.array
    spine_dend_avg_local_coactivity_rate_norm: np.array
    spine_dend_cluster_score: np.array
    spine_dend_coactive_num: np.array
    movement_spine_traces: list
    movement_spine_amplitude: np.array
    movement_spine_onset: np.array
    movement_dend_traces: list
    movement_dend_amplitude: np.array
    movement_dend_onset: np.array
    learned_movement_pattern: list
    spine_movements: list
    spine_movement_correlation: np.array
    spine_movement_reliability: np.array
    spine_movement_specificity: np.array
    dend_movements: list
    dend_movement_correlation: np.array
    dend_movement_reliability: np.array
    dend_movement_specificity: np.array
    local_movements: list
    local_movement_correlation: np.array
    local_movement_reliability: np.array
    local_movement_specificity: np.array
    spine_dend_movements: list
    spine_dend_movement_correlation: np.array
    spine_dend_movement_reliability: np.array
    spine_dend_movement_specificity: np.array
    rel_spine_vs_dend_move_corr: np.array
    spine_to_dend_correlation: np.array
    spine_to_nearby_correlation: np.array
